Goroutines optional
PettitWesley/amazon-kinesis-streams-for-fluent-bit pull request #2
Opened 2020-06-10 19:29 UTC by zackwine

- Add option to set goroutine flushes concurrency level
- Make the default use non-concurrent flushes
- Update progressive backoff logic to handle log spikes

2020-06-11 23:29 UTC, zackwine commented
@PettitWesley Please review these changes and let me know if this fits what you had in mind.

2020-06-12 07:51 UTC, PettitWesley requested changes
Thanks for working on this- Comments from first read through, will go over again on the weekend

2020-06-12 07:51 UTC, PettitWesley commented on fluent-bit-kinesis.go
> +	retries = 6
Retries should be configurable instead of hard-coded. I also think 6 is a bit high for that default value...

2020-06-12 07:51 UTC, PettitWesley commented on README.md
> +* `concurrency`: Specify a limit of concurrent go routines for flushing records to kinesis.  By default `concurrency` is set to `0` and records are flushed in the context of the calling fluentbit cor
> By default `concurrency` is set to `0` and records are flushed in the context of the calling fluentbit coroutine.

Your average Fluent Bit user will not know how coroutines work (or how Fluent Bit works). Something like this should intuitively make sense to people I think: "By default `concurrency` is set to `0` and records are flushed in Fluent Bit's single thread. This means that requests to Kinesis will block the execution of Fluent Bit as whole."

2020-06-15 07:15 UTC, PettitWesley commented
Did a second pass; couldn't find anything else to complain about.

2020-06-15 13:55 UTC, zackwine commented
I'll address the code review, and retest today

2020-06-15 22:00 UTC, PettitWesley commented
Ran the Kinesis integ tests, passed.

2020-06-16 14:00 UTC, zackwine commented
@PettitWesley  I ran several load tests with these changes, and verified `concurrency` and `concurrency_retires` work as expected.

2020-06-19 07:28 UTC, PettitWesley approved these changes
@zackwine Please raise a PR on the main repo for this new feature 🥳

2020-06-19 07:30 UTC, PettitWesley commented
Also, once we get around to re-implementing this plugin in C, I'm going to ask you to run your performance tests on that. Hopefully it can hit higher throughput.

2022-05-31 19:45 UTC, closed without merging